import { Language } from "../../Redux/profilesSlice";

export default {
    [`${Language.AMHARIC}`]: {
        engagments: "ተሳትፎዎች",
        amountofcalloriesburnedintotalpermonth: "በወር በጠቅላላው የተቃጠሉ ካሎሪዎች መጠን",
        sleep: "እንቅልፍ",
        water: "ውሃ",
        meal: "ምግብ",
        activities: "እንቅስቃሴዎች",
        monday: "ሰኞ",
        tuesday: "ማክሰኞ",
        wednesday: "እሮብ",
        thursday: "ሃሙስ",
        friday: "አርብ",
        saturday: "ቅዳሜ",
        sunday: "እሁድ",
        carbs: "ካርቦሃይድሬት",
        protiens: "ፕሮቲኖች",
        fats: "ቅባቶች",
        nutrientsandfiber: "ንጥረ ነገሮች",
        first: "መስከረም",
        second: "ጥቅምት",
        third: "ህዳር",
        fourth: "ታህሳስ",
        fifth: "ጥር",
        sixth: "የካቲት",
        seventh: "መጋቢት",
        eigth: "ሚያዝያ",
        ninth: "ግንቦት",
        tenth: "ሰኔ",
        eleventh: "ሃምሌ",
        twelvth: "ነሃሴ"
    },

    [`${Language.ENGLISH}`]: {
        engagments: "Engagments",
        amountofcalloriesburnedintotalpermonth: "Amount of calories burned in total per month",
        sleep: "Sleep",
        water: "Water",
        meal: "Meal",
        activities: "Activities",
        monday: "monday",
        tuesday: "tuesday",
        wednesday: "wednesday",
        thursday: "thursday",
        friday: "friday",
        saturday: "staturday",
        sunday: "sunday",
        carbs: "Carbs",
        protiens: "protiens",
        fats: "fats",
        nutrientsandfiber: "Nutrients",
        first: "Januray",
        second: "February",
        third: "March",
        fourth: "April",
        fifth: "May",
        sixth: "June",
        seventh: "July",
        eigth: "Auguest",
        ninth: "September",
        tenth: "October",
        eleventh: "November",
        twelvth: "December"

    },

    [`${Language.FRENCH}`]: {
        engagments: "engagement",
        amountofcalloriesburnedintotalpermonth: "Quantité de calories brûlées au total par mois",
        sleep: "dormir",
        water: "d;eau",
        meal: "repas",
        activities: "Activities",
        monday: "lundi",
        tuesday: "mardi",
        wednesday: "Mercredi",
        thursday: "jeudi",
        friday: "vendredi",
        saturday: "samedi",
        sunday: "dimanche",
        carbs: "carbs",
        protiens: "protéines",
        fats: "graisses",
        nutrientsandfiber: "Nutriments",
        first: "janvier",
        second: "février",
        third: "Mars",
        fourth: "avril",
        fifth: "mai",
        sixth: "juin",
        seventh: "juillet",
        eigth: "aout",
        ninth: "septembre",
        tenth: "octobre",
        eleventh: "novembre",
        twelvth: "décembre"
    }
}